### PR TITLE
Add PHP 5.6, 7.0 and HHVM support to travis tests.

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by jenssegers** [comment]
Looks like there are some issues with PHP7 and HHVM.

**Comment by vinkla** [comment]
I'll check it out.

**Comment by vinkla** [comment]
It seems this has to do with the coverage API. The service provider isn't tested and since the service provider requires at least PHP 5.4.7 it fails. Maybe we could drop support for 5.3 and I could help you setup service provider tests?

**Comment by vinkla** [comment]
I could push the updates to #110 if you want?

**Comment by jenssegers** [comment]
Is it related to the service provider? PHP 5.3 looks fine on Travis?

**Comment by vinkla** [comment]
I think this should be reverted back until we have green tests.

**Comment by jenssegers** [comment]
I added both 7.0 and HHVM to allow_failures. Carbon needs to fix their issues with PHP 7 as well. I will take a look at the HHVM error tonight.

**Comment by vinkla** [comment]
What about PSR-4 on the tests?

**Pull request merged**
