### PR TITLE
Added optional 2nd parameter to diffForHumans

### PR DESCRIPTION
**Pull request by thujohn**
Idea from https://github.com/briannesbitt/Carbon/pull/230

### CODE REVIEW

**Comment by jenssegers** [comment]
I think this should be added later, before the return https://github.com/thujohn/laravel-date/blob/master/src/Jenssegers/Date/Date.php#L134

**Comment by thujohn** [comment]
Do you prefer like this ?

**Comment by jenssegers** [comment]
Does it work? Can't you just do `return $ago`? Or am I missing something.

**Comment by thujohn** [comment]
Yes it works too.
I just took example from your code.

**Comment by jenssegers** [comment]
Do you know how to add it to the unit tests?

**Comment by thujohn** [comment]
I'm not sure how to test it but here is how I'm using it :
```Date::now()->diffForHumans($user->created_at, true)```

**Pull request merged**
