### PR TITLE
Add Service Provider and PSR-4 supported tests

### LINKED ISSUE #109: PSR-2 and PSR-4
What about adding PSR-2 and PSR-4 standards to this package? What do you think @jenssegers? I could help out with that.

### PR DESCRIPTION
**Pull request by vinkla**
I've added PSR-4 support to the tests.

This partially closes #109 and #114.

### CODE REVIEW

**Comment by vinkla** [comment]
@jenssegers I've removed hhvm tests and the tests now works fine.

**Comment by vinkla** [comment]
@jenssegers I've added a service provider test and dropped PHP `5.3` support.

**Comment by jenssegers** [comment]
I'm still not completely sure about the PSR4 support for tests, it just feels so unnecessary. Not even Laravel uses PSR4 in their tests.

**Comment by vinkla** [comment]
Why not? In this way we'll code the package source and the tests in the same way. The [The League of Extraordinary Packages](https://github.com/thephpleague/url/blob/master/composer.json), [Graham Campbell](https://github.com/GrahamCampbell/Laravel-Dropbox/blob/master/composer.json) (who is one of Laravel's maintainers) and many more does this already. Why shouldn't we? This update gives us better coverage tests :)

**Comment by vinkla** [comment]
@jenssegers have you had any time to think this through?

**Comment by vinkla** [comment]
@jenssegers have you had any time to think this through?

**Comment by vinkla** [comment]
@jenssegers have you decided? If you don't want it I understand. Please let me know!

**Comment by jenssegers** [comment]
Currently I don't really see the point in keeping tests PSR-4, sorry. I might come back to this later but will close it for now.

**Pull request closed without merging**
