### PR TITLE
Fix singular and plural nouns in Vietnamese

### PR DESCRIPTION
**Pull request by thangngoc89**
In Vietnamese, we don't distinguish and plural and singular nouns.
The previous translation are fine. But It leads to unexpected behaviour.
Please install this test repo to see the wrong behaviour
https://github.com/thangngoc89/test-laravel-date/tree/master

I really don't know why Travis failed on the second commit (just a small typo fix).

Here is some additional infomation:
- Replace en/date.php with vi/date.php (locale vi) it works as excepted.
- Replace vi/date.php with en/date.php (locale en) wrong behaviour.
-- 5 days ago shows as 1 day ago

### CODE REVIEW

**Comment by thangngoc89** [comment]
Related to this issues https://github.com/jenssegers/laravel-date/issues/65

**Comment by thangngoc89** [comment]
@jenssegers can you point out what the real problem is?Because if I replace en/date.php with vi/date.php (locale en) it works as excepted.

**Comment by jenssegers** [comment]
Don't really know why, it's the Symfony translator that makes the choices for the language file.

**Comment by thangngoc89** [comment]
Thank you for that infomation.

**Pull request merged**
